module.exports = {
    /* General */
    USER_JOINED_ROOM: 'USER_JOINED_ROOM',
    UPDATE_USERS_IN_ROOM: 'UPDATE_USERS_IN_ROOM',
    /* Client Messages */
    NEW_ROOM_CLIENT_MESSAGE: 'NEW_ROOM_CLIENT_MESSAGE',
    /* Server Messages */
    NEW_ROOM_SERVER_MESSAGE: 'NEW_ROOM_SERVER_MESSAGE',
    NEW_GLOBAL_SERVER_MESSAGE: 'NEW_GLOBAL_SERVER_MESSAGE',
    /* Notifications */
    NEW_ROOM_NOTIFICATION: 'NEW_ROOM_NOTIFICATION',
    NEW_GLOBAL_NOTIFICATION: 'NEW_GLOBAL_NOTIFICATION',
    /* Types */
    NOTIFICATION_TYPE_INFO: 'info',
    NOTIFICATION_TYPE_SUCCESS: 'success',
    NOTIFICATION_TYPE_WARNING: 'warning',
    NOTIFICATION_TYPE_ERROR: 'error',
};
